# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_su4st_1ApgJz_XZSWgd6SSrxpMK85gu
"""

import cv2 as cv

import matplotlib.pyplot as plt

import numpy as np

from google.colab.patches import cv2_imshow

image = cv.imread('/content/drive/MyDrive/lenna.png')
gray_image = cv.cvtColor(image, cv.COLOR_BGR2GRAY)

channels = [0]
histSize = [256]
range_im = [0, 256]
hist = cv.calcHist([gray_image], channels, None, histSize, range)

gs = plt.GridSpec(2, 2)
plt.figure(figsize=(10, 8))
plt.subplot(gs[0])
plt.imshow(gray_image, cmap = 'gray')
plt.subplot(gs[1])
plt.hist(gray_image.reshape(-1), 256, range_im)

lut = lambda i: 255 * (hist[:i.astype(int)].sum()/hist[:255].sum())

def lutT(x):
  copy = np.zeros(x.shape);
  i = 0
  j = 0
  while i < x.shape[0]:
    while j < x.shape[1]:
      copy[i,j] += lut(x[i,j]).astype(int)
      j += 1
    j = 0
    i += 1
  return copy

lut(gray_image[0,0]).astype(int)

result = lutT(gray_image)
result

plt.subplot(gs[0])
plt.imshow(gray_image, cmap = 'gray')
plt.subplot(gs[1])
plt.hist(gray_image.reshape(-1), 256, range_im)
plt.subplot(gs[2])
plt.imshow(result, cmap = 'gray')
plt.subplot(gs[3])
plt.hist(result.reshape(-1), 256, range_im)