# -*- coding: utf-8 -*-
"""Лабораторная работа №4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h69XDkv563fjfkZ3cPGjvQ9RGe4l3mn3
"""

# Commented out IPython magic to ensure Python compatibility.
import sys
#sys.path.append('../')
# %matplotlib inline
import matplotlib.pyplot as plt
import cv2 as cv
import numpy as np
#from utility import util

# Изменим стандартный размер графиков matplotlib
plt.rcParams["figure.figsize"] = [20, 16]

origin_image = cv.imread('/content/drive/MyDrive/Обработка изображений/unnamed.png');
gray_image = cv.cvtColor(origin_image, cv.COLOR_BGR2RGB)

plt.imshow(gray_image)

kernel = np.asarray([[1, 0, -1], [2, 0, -2], [1, 0, -1]])
filtered_image = cv.filter2D(gray_image, -1, kernel)

plt.imshow(filtered_image, cmap='gray')

ret, thresh1 = cv.threshold(gray_image, 115, 255, cv.THRESH_BINARY)
plt.rcParams["figure.figsize"] = [50, 50]
plt.imshow(thresh1)