# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QbRwWDdoraSiAe6B2vcfKeGOtPYNS8IU
"""

import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np

from matplotlib import colors
from matplotlib.colors import hsv_to_rgb

image = cv.imread('/content/drive/MyDrive/Обработка изображений/orange.JPG')
rgb_image = cv.cvtColor(image, cv.COLOR_BGR2RGB)

plt.imshow(rgb_image)
plt.show()

r,g,b = cv.split(rgb_image)
fig = plt.figure()
axis = fig.add_subplot(1, 1, 1, projection="3d")
pixel_colors = rgb_image.reshape((np.shape(rgb_image)[0]*np.shape(rgb_image)[1], 3))
norm = colors.Normalize(vmin=-1.,vmax=1.)
norm.autoscale(pixel_colors)
pixel_colors = norm(pixel_colors).tolist()
axis.scatter(r.flatten(), g.flatten(), b.flatten(), facecolors=pixel_colors, marker=".")
axis.set_xlabel("Red")
axis.set_ylabel("Green")
axis.set_zlabel("Blue")
plt.show()

red = rgb_image.copy()
red[:,:,1:] = 0

plt.imshow(red)
plt.show()

image_hsv = cv.cvtColor(rgb_image, cv.COLOR_RGB2HSV)

plt.imshow(image_hsv)
plt.show()

h, s, v = cv.split(image_hsv)
fig = plt.figure()
axis = fig.add_subplot(1, 1, 1, projection="3d")

axis.scatter(h.flatten(), s.flatten(), v.flatten(), facecolors=pixel_colors, marker=".")
axis.set_xlabel("Hue")
axis.set_ylabel("Saturation")
axis.set_zlabel("Value")
plt.show()

image_lab = cv.cvtColor(rgb_image, cv.COLOR_RGB2LAB)

plt.imshow(image_lab)
plt.show()

low_level_colors = np.array([137, 186, 192])
white_color = np.array([255, 255, 255])
low_square = np.full((10,10,3), low_level_colors, dtype=np.uint8) / 255
white_square = np.full((10,10,3), white_color, dtype=np.uint8) / 255

plt.subplot(1, 2, 1)
plt.imshow(hsv_to_rgb(low_square))
plt.subplot(1, 2, 2)
plt.imshow(hsv_to_rgb(white_square))
plt.show()

mask = cv.inRange(image_lab, np.array([110,110,110]), white_color)
result = cv.bitwise_and(rgb_image, rgb_image, mask=mask)

plt.subplot(1, 2, 1)
plt.imshow(mask)
plt.subplot(1, 2, 2)
plt.imshow(result)
plt.show()